README.md

The `error_on` method was deprecated in RSpec 3.0, so I replaced it with the equivalent line for 3.0+ (starting at line 888). My editor also removed some trailing whitespace throughout the document, and I caught a typo on line 433

Remove deprecated error_on method

---

README.md

Just  a minor fix in a `pre` element
before
after

Fix syntax highlight by adjust on tabulation

---

README.md

The example provided was syntactically incorrect. This change is fixing the syntax.

Fix syntax is negative expectation example

---

README.md

It's being enforced by RSpec/LeadingSubject cop.

Add leading subject rule

---

README.md

The example is running validation on the wrong object
Maybe we should replace `create` with `build` as well, or remove the `valid?` call, as the `create` will run the validations anyway

Fix typo in an example

---

README.md

FactoryGirl was renamed to FactoryBot, so this updates all the references in the style guide

Rename FactoryGirl following the original library rename

---

README.md

`RSpec/Be` cop currently enforces this behavior and [RSpec may actually deprecate the usage of be without arguments](https://github.com/rspec/rspec-expectations/issues/761)

Avoid using `be` matcher without arguments

---

README.md

The mentioned style guide is Rails, not RSpec. Not sure if the URL and even the name should reflect RuboCop HQ

Fix rails-style-guide reference

---

README.md

ruby-style-guide and rails-style-guide use different formatting and
structure. This is changes the guide style and formatting to match the
other guides.
* added Table of Contents, re-arranged the guide under major topics
* aggregated the good and bad snippets
* added `[link]`'s
* fixed some typos

Unify the style with the other guides

---

README.md

[Fix #28] Allow context to begin with 'with' or 'without'

---

README.md

Improve the rule defining what should be in the context description
exactly and how it should complete the example description.

Improve the wording of the context description rule.

---

README.md

Removed branches: `gh-pages`.
Borrowed small wording changes from `add_more_syntactical_style`.
Borrowed softened contribution guideline tone from `softened_tone` (and also `ruby-style-guide`/`rails-style-guide`).
Additionally:
- added license information to match those of `ruby-style-guide` and `rails-style-guide`;
- added credit to ReachLocal for long-term maintenance
Resolves #36

Gathered useful changes from stale branches

---

README.md

With the [introduction of `aggregate_failures` feature in RSpec 3.3](http://rspec.info/blog/2015/06/rspec-3-3-has-been-released/) there are no strong arguments left to stick to the strict style, as the output remains the same, while context initialization costs are reduced.
Initially, this was brought up in #11, this change is partially based on it.

Relax "one expectation per example" rule

---

README.md

RSpec defines `specify`:
> Useful for when your docstring does not read well off of `it`.
RSpec.describe MyClass do
specify "#do_something is deprecated" do
Example output:
#force
for ordering options
CLI `--seed 37` forces order and seed

Expand on the `specify` and `it` differences

---

README.md

The rule relates to naming, not layout.

Move "should in `it`" to proper section

---

README.md

Stubbing methods of the object under test is a code smell and often indicates a bad design of the object itself.
Originated in #32

Discourage stubbing the subject

---

README.md

It's quite fair to recommend shoulda-matchers, it's about to hit a major release, and it's **the** most known third-party RSpec matcher gem since we do already recommend FactoryBot and TimeCop.
Relates to #33

Recommend using shoulda-matchers

---

README.md

From [RSpec docs](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance):
> This feature is sometimes useful when working with legacy code, though
> in general we discourage its use.
Fixes #42

Discourage the use of *_any_instance_of

---

README.md

https://github.com/lelylan/betterspecs are not actively maintained, but
contain a lot of useful material that fits this style guide quite well.
The license of Betterspecs allow for derivative work, and there were [no
objections](https://github.com/lelylan/betterspecs/issues/153) on
picking the material to this guide.
- Translations to the other languages originally present in the original (e.g. [fr](https://github.com/lelylan/betterspecs/blob/gh-pages/fr.html), [jp](https://github.com/lelylan/betterspecs/blob/gh-pages/jp.html), [zh_ch](https://github.com/lelylan/betterspecs/blob/gh-pages/zh_cn.html), ...), that would be problematic without the knowledge of most of those languages and considering wording changes of the original rules I've made
- Links to the books and presentations
- …

Merge rules and recommendations from betterspecs.org

---

README.md

Could instead escape single quotes if preferred.

Fix quoting with description with single quotes.

---

README.md

`spec_helper.rb` is included by default when RSpec [is properly configured](https://github.com/rspec/rspec/wiki#configure-rspec), e.g. when `.rspec` contains `--require spec_helper`.
Fixes #60

Drop outdated Require spec_helper recommendation

---

README.md

Change `he` to `they` in the explanatory text referring to 'The Developer'. The description works fine without assuming the developer is male.

Refer to 'The Developer' as 'they' instead of 'he'

---

README.md

Some ruby strings were being started with single quote but ended with tilde, which is invalid and screws up syntax highlighting.

Fix mistake of using tilde instead of single quote

---

README.md

Align the guide to mention corresponding RuboCop extension like the [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide) mentions RuboCop itself.
Fixes #83

Mention rubocop-rspec

---

README.md

Since it's been around for almost 7 years, it doesn't make sense to refer to the `expect` syntax as 'new'.
http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/

Update wording for when to use `expect` syntax

---

README.md

Since the subsequent line concerns recipients, this seem to be a mistake.

Correct mistake in email advice

---

README.adoc

As discussed in https://github.com/rubocop-hq/rubocop-rspec/pull/757
Rather than attempt to have a definitive list of acceptable prefixes, let's emphasize the intention of this guidance.
@pirj @josephan @dgollahon

Relax guidance for context wording

---

README.adoc

Constants defined in a block are defined in a global namespace, and are not cleared up between examples.
If several examples may define a `DummyClass`, instead of being a blank slate class as it will be in the first example, subsequent examples will be reopening it and modifying its behaviour in unpredictable ways.
Even worse when a class that exists in the codebase is reopened.
Anonymous classes are fine since they don't result in global namespace name clashes.
Related [`RSpec/LeakyConstantDeclaration`](https://github.com/rubocop-hq/rubocop-rspec/pull/765) cop (follow the link for a lot of reasoning behind it).
More accessible representation of the added guideline https://github.com/rubocop-hq/rspec-style-guide/blob/add-leaky-constant-guideline/README.adoc#declare-constants

Add Declare Constants guideline

---

README.adoc

Fix example and a type in Declare Constants guideline.

Fix Declare Constants code example

---

README.adoc

Implicit syntax is discouraged to use by RSpec Core team and the majority of voters.
There were no good arguments for using the syntax except for brevity and avoiding repetition, but there are better options to achieve the same goal, e.g. by extracting the lengthy block to methods (instead of putting it inside the lambda).
Fixes #76
Better viewed as https://github.com/rubocop-hq/rspec-style-guide/blob/add-implicit-block-expectation-guideline/README.adoc#implicit-block-expectations
References:
https://www.reddit.com/r/ruby/comments/cejl3q/call_for_discussion_rspec_implicit_block/
https://blog.rubystyle.guide/rspec/2019/07/17/rspec-implicit-block-syntax.html
https://github.com/rubocop-hq/rspec-style-guide/issues/76
https://lobste.rs/s/e8yxmd/call_for_discussion_rspec_implicit_block

Add Implicit Block Expectation guideline

---

README.adoc

This rewording relaxes the guide slightly while (I believe) preserving the intent. Sometimes a preposition other than `when`, `with`, or `without` allows the name to better express the developer's intent. `before` and `after` convey _flow of time_ more clearly—see https://github.com/rubocop-hq/rubocop-rspec/pull/861 for an example of that.
Explicitly mentioning `...or similar` expresses that this guideline should not be taken as exhaustive, as long as context naming creates a sentence with proper grammar. This extends the efforts of https://github.com/rubocop-hq/rspec-style-guide/pull/100 by making extra-clear that other values are permitted. Other possible valid values may include `for`, `in`, `while`, or `during`.
---
A note on the use of `adpositional phrase` instead of `propositional …

Relax constraints on context naming

---

README.adoc

It's simply a tiny typo error.
For a better community-driven documentation.

Fix typo at DRY section

---

README.adoc

Previously the comment demonstrating the documentation output did not match the context descriptions used in the code example.

Fix typo in Context Descriptions section

---

README.adoc

https://rspec.rubystyle.guide/ suggests forking the project to contribute but didn't actually provide a link to the project itself. This fixes that.

Link to the GitHub project in "How to Contribute?"

---

README.adoc

https://rspec.rubystyle.guide/#describe-the-methods already exists
Kept the old anchor to refer to "Describe the Methods" guideline

Remove redundant guideline

---

README.adoc

As I've mentioned in [this blog post](https://simon.fish/blog/subject-to-change-effective-use-of-rspec.html), I think the examples should encourage making the `subject` always point to the object or method under test directly. There are some examples of cases in the docs that don't reflect this, which this PR changes.
Whether the examples use `expect(subject)` or `is_expected` is up for debate, but I tend to prefer `is_expected` only for one_liner examples like `it { is_expected.to have_attributes(name: 'Simon') }`.
It could be argued that these examples are only meant to highlight the difference between bad and good syntax and structure, and thus don't need to pay as much attention to the wider usage of the library where it isn't directly relevant to the lesson at hand. However, I feel …

Refer to the method call under test with `subject`

---

README.adoc

Added section on the declaration order of `subject`, `let!`/`let` and `before`/`after` hooks to the [Example Group Structure](https://github.com/rubocop/rspec-style-guide#example-group-structure) section.
Also, moved [Leading Subject] to the [Example Group Structure](https://github.com/rubocop/rspec-style-guide#example-group-structure) section, as mentioned [below](https://github.com/rubocop/rspec-style-guide/pull/135#pullrequestreview-1658274861).
Resolves https://github.com/rubocop/rspec-style-guide/issues/134

Added section on the declaration order of subject, let!/let and before/after hooks

---

README.adoc

A small detail was found in the Context Cases section of the documentation (see issue above for more details). The `# good` example was not in alignment with best practices.
* Context Cases example section

Fixes Context Cases example
